### ISSUE TITLE
Facing Many issues in Jcanvas.

### ISSUE THREAD

**Issue by satanand7** [caleb531/jcanvas-website#2]
1. Can not getting the actual point where I click or drag on canvas.
Comments : I try to get the clicked pixel from the whole window on canvas. I have to use below of code. Can you have any option on your canvas to getting clicked point of canvas. Because when we use canvas on scrollable div then i cant get the actual point of clicked area.
 `
function relMouseCoords(event) {
                    var totalOffsetX = 0;
                    var totalOffsetY = 0;
                    var canvasX = 0;
                    var canvasY = 0;
                    var currentElement = this;

                    do {
                        totalOffsetX += currentElement.offsetLeft - currentElement.scrollLeft;
                        totalOffsetY += currentElement.offsetTop - currentElement.scrollTop;
                    } while (currentElement = currentElement.offsetParent)

                    canvasX = event.pageX - totalOffsetX;
                    canvasY = event.pageY - totalOffsetY;
                    alert(canvasX);
                    return {x: canvasX, y: canvasY}

                }

`
2. Fill style have transparent option but if line surface is closed then I can not select the inner layer indexes of the for dragging. 
3. Can not Plot any layer or pixel on (0, 0) coordinate because this is not visible on canvas.
Comment:- Actually I want to add an image on canvas that can act as background image of the canvas.
4. Can not redraw the canvas using JSON value of the canvas.
Comment:-  I have saved entire JSON Object of canvas in my database. But cant find the way to re-create the jcanvas from the data.
`
            seen=[];
                    json = JSON.stringify(canvas, function (key, val) {
                        if (typeof val == "object") {
                            if (seen.indexOf(val) >= 0)
                                return
                            seen.push(val)
                        }
                        return val
                    })
                    alert(json);
`  
5. Want to plot layer after zooming the jcanvas but when I zoom the canvas the pixel value where i click my be different i think. 
6. Also rotation is not also working as expected because I cant find the respective axis that the object is rotating.
[h.html.zip](https://github.com/caleb531/jcanvas-website/files/882762/h.html.zip)

 
I have uploaded the whole code in attachment. Please review and let me know the update.

**Comment by caleb531** [comment]
@satanand7, you have many questions. Allow me to tackle them one at a time:

## 1. Retrieving cursor coordinates

You can use `layer.eventX` and `layer.eventY` to get the cursor coordinates where the layer was clicked or dragged. You can access them from the `layer` object passed to any jCanvas mouse event (`click`, `mousedown`, `drag`, etc.). See[ this section of the documentation](https://projects.calebevans.me/jcanvas/docs/eventProperties/#the-eventx-and-eventy-properties).

## 2. fillStyle transparency

I'm not quite sure what you mean by this. Could you please provide a code example that reproduces the behavior you describe? (something I can run in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/) would be preferable)

## 3. Layer positioning

Drawings in jCanvas (rectangles, arcs, images, etc.) are drawn from the center by default. In other words, the (x, y) coordinates for each shape lies at the center of that shape. You can change this to make (x, y) the top-left corner (as you so desire) by setting `fromCenter: false` on your layer.

## 4. Serialization

jCanvas currently does not have any built-in methods for serialization, so you must write your own (it's not hard). To save/restore jCanvas objects, you must serialize them to JSON objects before storing them (locally, on the server, etc.) and then you must deserialize them when you restore them to the canvas. Furthermore, jCanvas layers are actually stored on the canvas via jQuery's `$.data` function, and not set directly as DOM properties. If you really want access to all of that data (including layers and transform data), you can use `$.data($myCanvas[0], 'jCanvas')`.

However, every jCanvas layer is a JS object containing both JSON-serializable properties (`x`, `y`, `width`, `height`, `draggable`, etc.) and non-JSON-serializable properties (all event callbacks, reference to the canvas element, etc.). Therefore, you must pick out those serializable jCanvas properties which are sufficient for recreating those layers in your particular application. You shouldn't need to serialize event callbacks, since those don't ever change on a per-layer basis.

The easiest way to write your own serialization functions is to create an array containing the names of the properties you want to store for each layer, then for every layer, loop through that list of property names and create a new object with only those properties from the layer. Then you serialize that object as JSON (using JSON.stringify) and store that on the server (or locally). To deserialize a layer, you can use JSON.parse combined with the addLayer() method (assuming the type property is present on each deserialized layer object).

## 5. Scaling and clicking 

When you scale the canvas with a jCanvas method like `scaleCanvas`, the internal coordinate system is scaled by that factor, while the physical canvas dimensions remain the same. I mentioned above that you can use `layer.eventX` and `layer.eventY` to retrieve the current cursor coordinates after a mouse event. To factor in scaling, you must divide `layer.eventX` and `layer.eventY` by the scale factor. For instance, if you zoom in to a scale of 1.25, you must use `layer.eventX / 1.25` and `layer.eventY / 1.25`. Of course, if you store the current scale value into a variable, then you can perform this division dynamically, whatever the current scale value is.

## 6. Rotation

When you use a method like `rotateCanvas` without `x` and `y` arguments, the canvas will rotate around the top-left corner of the canvas. In other words, the top-left corner of the canvas (i.e. (0, 0)) is the center of rotation. You can override this to be the center of the canvas or whatever else by passing `x` and `y` properties to `rotateCanvas`.

Anyway, I hope that all helps.
Caleb
